# 所有配置均移到nacos配置中心 ，这里只是示例配置，这里是什么配置，nacos配置中心也是对应的配置
# nacos自己的配置详见config-debug.yaml文件

host: "" # 服务主机ip 或域名 ，本地调试默认127.0.0.1
name: "goods_web" # 服务名称
port: 8082 # 服务端口 ，默认8082
tags: ["", "", "", ""] #服务标签
user_srv: # 用户服务配置
  host: "" # 用户服务主机ip 或域名 ，本地调试默认127.0.0.1,但是注意consul的host要和这里一致，对外可访问的IP
  port: 50051 # 用户服务端口 ，默认50051
  name: "" # 用户服务名称 ，为你自己在consul注册的服务名称

jwt: # jwt配置
  key: "{*4d5!|pQ]_E3GGkAQZF" # jwt密钥

consul: # consul配置
  host: "" # consul主机ip 或域名 ，为你自己的consul主机ip 或域名
  port: 8500 # consul端口 ，默认8500
